### ISSUE TITLE
Connection getting error on click search function not working and database not getting

### ISSUE THREAD

**Issue by aakashpatel1995** [aakashpatel1995/Postgres-Aws#1] opened 2020-06-29 01:48 UTC
database is not connecting and database is not able to fetch

**Comment by dhruvinparikh93** [comment] 2020-06-29 01:58
@aakashpatel1995  Please add the steps to run the project and reproduce the error.

**Comment by aakashpatel1995** [comment] 2020-06-29 02:09
@dhruvinparikh93 added steps in readme 

screen is showing but when try to do onclick function it not works it shows error

**Comment by aakashpatel1995** [comment] 2020-06-29 02:57
@dhruvinparikh93 still data is not coming or showing

**Comment by dhruvinparikh93** [comment] 2020-06-29 03:52
Fixed in [PR](https://github.com/aakashpatel1995/Postgres-Aws/pull/4) . @aakashpatel1995 can review and merge.

**Comment by dhruvinparikh93** [comment] 2020-07-05 23:51
@aakashpatel1995 Close if the issue is solved

**Closed** 2020-07-09 01:17 UTC
